---
title: "Progressive Union"
author: "Jessica Bonnie"
date: "5/10/2022"
output: html_document
---

```{r prep, echo=FALSE,warning=FALSE,include=FALSE}

require(tidyr)
require(ggplot2)
require(data.table)
require(openssl)
require(dplyr)
require(optparse)
require(callr)
codelib<-'/home/jessica/dandd/dev-dandD/lib/'
source(file.path(codelib,'plot_progressive.R'))

outdir<-'/scratch4/blangme2/jessica/dandd/RECOMB'

```


```{bash}
tag=ecoli
outdir=/home/jbonnie1/scr16_blangme2/jessica/dandd/RECOMB/${tag}
sketchdir=/home/jbonnie1/scr16_blangme2/jessica/dandd/RECOMB/${tag}
genomedir=/home/jbonnie1/scr16_blangme2/jessica/data/${tag}

cd ${outdir}
python /home/jbonnie1/scr16_blangme2/jessica/dandd/dev-dandD/lib/dandd_cmd.py tree -s ${tag} -o ${outdir} -k 14 --datadir ${genomedir} --registers 30

tree_pick=${outdir}/${tag}_10_dashing_dtree.pickle

python /home/jbonnie1/scr16_blangme2/jessica/dandd/dev-dandD/lib/dandd_cmd.py info -d ${tree_pick} -o ${outdir}/ksweep_dashing.csv --mink 2 --maxk 32

python /home/jbonnie1/scr16_blangme2/jessica/dandd/dev-dandD/lib/dandd_cmd.py tree -s ${tag} -o ${outdir} -k 14 --datadir ${genomedir} --exact

tree_pick=${outdir}/${tag}_10_kmc_dtree.pickle
tree_pick=/home/jbonnie1/scr16_blangme2/jessica/dandd/RECOMB/ecoli/ecoli_10_kmc_dtree.pickle
python /home/jbonnie1/scr16_blangme2/jessica/dandd/dev-dandD/lib/dandd_cmd.py info -d ${tree_pick} -o ${outdir}/ksweep_kmc.csv --mink 2 --maxk 50

tree_pick=${outdir}/${tag}_10_dashing_dtree.pickle
python /home/jbonnie1/dandd/dev-dandD/lib/dandd_cmd.py progressive -d ${tree_pick}  -n 30 #-o ${outdir}/${tag}_progu30.csv
```


```{r heaps}



plot_scatter <- function (item, ytitle, filename, heap, alpha, param, plotlog=T) {
    param = latex2exp::TeX(param)
    if (abs(alpha) <= 1) {
        color_heap = "green"
    } else {
        color_heap = "red"
    }
    pl = ggplot(data = item, aes(x = x, y = y, color="Items")) +
        geom_point()+
        geom_line(data=heap,aes(x=x, y=y, color="Heap's law"), alpha=0.5)+
        theme_classic() +
        scale_color_manual(values=c(color_heap, "#000000"))+
        xlab("No. of genomes") +
        ylab(ytitle) + 
        ggtitle(param) +
        theme_bw(base_size = 16) + 
        theme(legend.text = element_text(size=5), plot.title =
              element_text(color="black", size=14))
    if (plotlog) {
       pl = pl + coord_trans(y='log10')#,x='log10')
    }
    plot(pl)
    #ggsave(filename=file.path(DIROUT, filename), plot=pl)
}

# heaps <- function(progu.df){
heaps <- function(ksweep.df){
  # progu.df <- group_by (ngenmutate(progu.df, av)
 avg.ksweep <- ksweep.df %>%
   group_by(ordering) %>% 
   mutate(delta_delta=delta_pos - lag(delta_pos, default = delta_pos[1])) %>%
   ungroup() %>% group_by(ngen) %>% 
   summarize(mean_delta=mean(delta_pos), mean_delta_delta2 = mean(delta_delta)) %>%
   mutate(mean_delta_delta1 = mean_delta - lag(mean_delta, default = mean_delta[1]))
  View(avg.ksweep)
  new_item <- avg.ksweep$mean_delta_delta1
  N=length(new_item)
# ALPHA
x = 2:N
model = lm(log(new_item[x])~log(x))
#str(summary(model))
#summary(model)
adj.r.sq = summary(model)$adj.r.squared
x_h = seq(2,N,length.out=1000)
y_h = exp(model$coefficients[1])*x_h^(model$coefficients[2])
alpha = abs(model$coefficients[2])
print(alpha)
heap = data.frame(x=x_h,y=y_h)
param = paste0("$\\alpha = $", signif(alpha, digits=4))
plot_scatter(data.frame(x=2:N,y=new_item[2:N]), "No. of new items", 
             paste0("new_items.png"), heap, alpha, param)
plot_scatter(data.frame(x=2:N,y=new_item[2:N]), "No. of new items", 
             paste0("new_items_log.png"), heap, alpha, param, plotlog=T)

}
```


```{r draw_ecoli, cache=TRUE}
tag='ecoli'
outdir='/home/jbonnie1/scr16_blangme2/jessica/dandd/RECOMB'

ksweep_ecoli_dashing <- read.csv(file.path(outdir,tag,"ksweep_dashing.csv")) %>% mutate(tool="dashing") %>% filter(ngen==max(ngen))
ksweep_ecoli_kmc <- read.csv(file.path(outdir,tag,"ksweep_kmc.csv"))  %>% mutate(tool="kmc") %>% filter(ngen==max(ngen))
# ksweep_ecoli <- bind_rows(ksweep_ecoli_kmc, ksweep_ecoli_dashing) 


ggplot() + geom_line(data = ksweep_ecoli_kmc, aes(x=kval, y=delta_pos, color="ecoli"))

ecoli_progu <- read.csv(file.path(outdir,tag,"ecoli_progu30.csv")) %>% rename(delta_pos=delta)

```



```{bash}
tag=salmonella
outdir=/home/jbonnie1/scr16_blangme2/jessica/dandd/RECOMB/${tag}
sketchdir=/home/jbonnie1/scr16_blangme2/jessica/dandd/RECOMB/${tag}
genomedir=/home/jbonnie1/scr16_blangme2/jessica/data/${tag}
codelib=/home/jbonnie1/dandd/dev-dandD/lib/

python ${codelib}/dandd_cmd.py tree -s ${tag} -o ${outdir} -k 14 --datadir ${genomedir}
tree_pick=${outdir}/${tag}_10_dashing_dtree.pickle

python ${codelib}/dandd_cmd.py info -d ${tree_pick} -o ${outdir}/dashing_ksweep.csv --mink 2 --maxk 32
tree_pick=${outdir}/${tag}_10_dashing_dtree.pickle
python ${codelib}/dandd_cmd.py tree -s ${tag} -o ${outdir} -k 14 --datadir ${genomedir} --exact
tree_pick=${outdir}/${tag}_10_kmc_dtree.pickle
python ${codelib}/dandd_cmd.py info -d ${tree_pick} -o ${outdir}/ksweep_kmc.csv --mink 2 --maxk 50

cd ${outdir}
tree_pick=${outdir}/${tag}_10_dashing_dtree.pickle
python ${codelib}/dandd_cmd.py progressive -d ${tree_pick} -n 30 
```


```{r draw_salmon6, cache=TRUE}
tag='salmonella'
outdir='/home/jbonnie1/scr16_blangme2/jessica/dandd/RECOMB'

ksweep_salmon_kmc <- read.csv(file.path(outdir,tag,"ksweep_kmc.csv")) %>% filter(ngen==max(ngen))

#delta_salmon<- fread(file.path(outdir,tag,paste0(tag,"_progu30.csv"))) %>% rename(delta_pos=delta, ngenomes=ngen)

#salmon.gg<-plotProgressiveUnion(species=tag, out = outdir, delta = delta_salmon, nshow=5)
#salmon.gg

ggplot() + geom_line(data = ksweep_salmon_kmc,aes(x=kval, y=delta_pos, color="salmonella")) + geom_line(data = ksweep_ecoli_kmc, aes(x=kval, y=delta_pos, color="ecoli"))

salmon_progu <- read.csv(file.path(outdir,tag, "salmonella_progu30_10_dashing.csv")) %>% rename(delta_pos=delta)

```



```{bash}
tag=human
outdir=/home/jbonnie1/scr16_blangme2/jessica/dandd/RECOMB/${tag}
sketchdir=/home/jbonnie1/scr16_blangme2/jessica/dandd/RECOMB/${tag}
genomedir=/home/jbonnie1/scr16_blangme2/jessica/data/${tag}

python /home/jbonnie1/scr16_blangme2/jessica/dandd/dev-dandD/lib/dandd_cmd.py tree -s ${tag} -o ${outdir} -k 18 --datadir ${genomedir}
tree_pick=${outdir}/${tag}_12_dashing_dtree.pickle
python /home/jbonnie1/scr16_blangme2/jessica/dandd/dev-dandD/lib/dandd_cmd.py info -d ${tree_pick} -o ${outdir}/ksweep_dashing.csv --mink 2 --maxk 32

python /home/jbonnie1/scr16_blangme2/jessica/dandd/dev-dandD/lib/dandd_cmd.py tree -s ${tag} -o ${outdir} -k 18 --datadir ${genomedir} --exact
tree_pick=${outdir}/${tag}_12_kmc_dtree.pickle
python /home/jbonnie1/scr16_blangme2/jessica/dandd/dev-dandD/lib/dandd_cmd.py info -d ${tree_pick} -o ${outdir}/ksweep_kmc.csv --mink 2 --maxk 37

#python /home/jbonnie1/scr16_blangme2/jessica/dandd/dev-dandD/lib/dandd_cmd.py progressive -d ${tree_pick}  -n 30 -o ${outdir}/${tag}_progu30.csv
```



```{r draw_human, cache=TRUE}
tag='human'
outdir='/home/jbonnie1/scr16_blangme2/jessica/dandd/RECOMB'

# ksweep_human_dashing <- read.csv(file.path(outdir,tag,"ksweep_dashing.csv")) %>% mutate(tool="dashing") %>% filter(ngen==max(ngen))
ksweep_human_kmc <- read.csv(file.path(outdir,tag,"ksweep_kmc.csv"))  %>% mutate(tool="kmc") %>% filter(ngen==max(ngen))
# ksweep_human <- bind_rows(ksweep_human_kmc, ksweep_human_dashing) 


ggplot() + geom_line(data = ksweep_human_kmc, aes(x=kval, y=delta_pos, color="human"))

ggsave(filename='human_progu.pdf',
       plot=humanprogu ,
       device = cairo_pdf, 
       dpi = 1200, 
       width = 16,
       height = 10, 
       units = "cm")

```

```{r draw3}
ggplot() + geom_line(data = filter(ksweep_ecoli_kmc,kval<=37), aes(x=kval, y=delta_pos/max(delta_pos), color="ecoli")) +
  geom_line(data = filter(ksweep_salmon_kmc,kval<=37), aes(x=kval, y=delta_pos/max(delta_pos), color="salmonella")) +
  geom_line(data = ksweep_human_kmc, aes(x=kval, y=delta_pos/max(delta_pos), color="human")) + theme_bw()


```




```{r humanloess}

loess_human<-loess(formula=delta_pos~ngenomes,data = delta_human)
delta_human %>% filter(delta_pos<.975*predict(loess_human,ngenomes)) %>% View()

human.dt <- delta_human %>% data.table() %>%
  group_by(ordering) %>% 
  # add column holding slope of delta from each genome to the next in an ordering
  mutate(slope = (delta_pos - lag(delta_pos)) / (ngenomes - lag(ngenomes))) %>% 
  mutate(global_mean=(max(delta_pos)-min(delta_pos))/(max(ngenomes)-min(ngenomes))) %>%
  # mutate(mean=mean(slope,na.rm = TRUE)) %>%
  filter((slope < (24/25)*global_mean | slope > (26/25)*global_mean ) & slope !=0) %>%
  #mutate(gset=list(order_human[[ordering]][1:ngenomes])) %>%
  ungroup() 
test <- unlist(lapply(seq(1,12), function(x){
  human.tmp<- human.dt %>% rowwise() %>% mutate(tmp=unlist(x %in% gset))
  return(sum(unlist(human.tmp$tmp)))
}))
test
which(test > max(test)-2)


```