
```{r prep, echo=FALSE,warning=FALSE, include=FALSE}

require(tidyr)
require(ggplot2)
require(data.table)
require(openssl)
require(dplyr)
require(optparse)
require(callr)
require(codetools)
codelib<-'/home/jbonnie1/dandd/dev-dandD/lib/'
source(file.path(codelib,'plot_progressive.R'))

outdir<-'/home/jbonnie1/scr16_blangme2/jessica/dandd/scratch/HVSVC2'

```


## Run random orderings for 10 genomes with only SNVs

```{bash, eval=FALSE}
outdir=/scratch16/blangme2/jessica/dandd/scratch/HVSVC2
tag=trio
filelist=/scratch16/blangme2/jessica/data/HVSVC2/consensus_mom_fchild_and_onef.txt
#_HG0111|
grep -E "(_HG00513|_HG00514|_HG01114)" /home/jbonnie1/scr16_blangme2/jessica/data/HVSVC2/consensus_fastas.txt > ${filelist}

sketchdir=${outdir}/sketchdb

python /scratch16/blangme2/jessica/dandd/dev-dandD/lib/dandd_cmd.py tree -s ${tag} -f ${filelist} -o ${outdir} -k 19 |& tee ${outdir}/${tag}_trio.log

tree_pick=/scratch16/blangme2/jessica/dandd/scratch/HVSVC2/trio_6_dashing_dtree.pickle

python /scratch16/blangme2/jessica/dandd/dev-dandD/lib/dandd_cmd.py progressive -d ${tree_pick} -n 300 -o ${outdir}/${tag}_progu.csv

#../scratch/progressive_union/sketches/HVSVC2/k20/ngen1/allvar_HG00513_1.fasta.gz.w.20.spacing.20.hll

```



```{r draw_graphs1, cache=TRUE, echo=FALSE, eval=FALSE}
tag='trio'
ngenome=6

delta_trio<-read.csv('/scratch16/blangme2/jessica/dandd/scratch/HVSVC2/trio_progu.csv') %>% 
  rename(delta_pos=delta, ngenomes=ngen)
plotProgressiveUnion(species=tag, out = outdir, delta_trio, nshow=10)


```

```{r abba, cache=TRUE}
abba.trio <- read.csv('/scratch16/blangme2/jessica/dandd/scratch/HVSVC2/trio_abba.csv')
abba.trio$added <- apply(select(abba.trio,-step), 1, function(data)
   names(which(data == 0)))


ggplot(abba.trio) + geom_boxplot(aes(x=as.factor(step),y=deltadelta)) + scale_y_log10()
# abba.trio %>% pivot_longer(contains("HG"),names_to="who",values_to = "value")
```


```{r abba2, cache=TRUE}
ggplot(abba.trio) + geom_boxplot(aes(x=as.factor(step),y=deltadelta, color=as.factor(HG00514_1))) + geom_point(aes(x=as.factor(step),y=deltadelta, color=as.factor(HG00514_1))) + scale_y_log10() 
ggplot(abba.trio) + geom_boxplot(aes(x=as.factor(step),y=deltadelta, color=as.factor(HG00514_2))) + geom_point(aes(x=as.factor(step),y=deltadelta, color=as.factor(HG00514_2))) + scale_y_log10()
```

```{r facet}
abba.trio$added_before <- factor((abba.trio$HG00513_1 == 1) + (abba.trio$HG00513_2 == 1))
dfsumm <- abba.trio %>% group_by(step) %>% summarise(mean=mean(deltadelta), sd=sd(deltadelta), median=median(deltadelta))
dfj <- inner_join(abba.trio, dfsumm)
ggplot(dfj %>% filter((HG00514_1 == 0 | HG00514_2 == 0) & step >= 2 & step <= 4), aes(y=(deltadelta-mean)/sd, x=added_before, color=added_before)) + geom_jitter(height=0) + facet_grid(step ~ (HG00514_1 == 0))


```
```{r explode, cache=TRUE, eval=FALSE, echo=FALSE}
abba.trio %>% filter(HG00514_1 == 0 & step==3 & HG00513_1 == 1 & HG00513_2 == -1) -> mom1
abba.trio %>% filter(HG00514_1 == 0 & step==3 & (HG00513_1 == 1 | HG00513_2 == 1)) -> allmommy
abba.trio %>% filter(HG00514_1 == 0 & step==3 & HG00513_1 == -1 & HG00513_2 == 1) -> mom2
abba.trio %>% filter(HG00514_1 == 0 & step==3 & HG00513_1 == -1 & HG00513_2 == -1) -> nomommy
nomommy$deltadelta %>% unique()



```


```{r mutate, cache=TRUE, echo=FALSE, eval=FALSE}

abba.trio$Mom1_ChildMat <- ifelse(abba.trio$HG00513_1 %in% c(0,1) & abba.trio$HG00514_1 == -1,1,0)
abba.trio$Mom2_ChildMat <- ifelse(abba.trio$HG00513_2 %in% c(0,1) & abba.trio$HG00514_1 == -1,1,0)
abba.trio$Mom_ChildMat <- ifelse((abba.trio$HG00513_1 & abba.trio$HG00513_2) %in% c(0,1) & abba.trio$HG00514_1 == -1,1,0)
abba.trio$ChildMat_Mom1 <- ifelse(abba.trio$HG00514_1 %in% c(0,1) & abba.trio$HG00513_1 == -1,1,0)
abba.trio$ChildMat_Mom2 <- ifelse(abba.trio$HG00514_1 %in% c(0,1) & abba.trio$HG00513_2 == -1,1,0)
abba.trio$ChildMat_Mom <- ifelse((abba.trio$HG00514_1) %in% c(0,1) & (abba.trio$HG00513_1 & abba.trio$HG00513_2) == -1,1,0)

abba.trio$Mom1_ChildPat <- ifelse(abba.trio$HG00513_1 %in% c(0,1) & abba.trio$HG00514_2 == -1,1,0)
abba.trio$Mom2_ChildPat <- ifelse(abba.trio$HG00513_2 %in% c(0,1) & abba.trio$HG00514_2 == -1,1,0)
abba.trio$Mom_ChildPat <- ifelse((abba.trio$HG00513_1 & abba.trio$HG00513_2) %in% c(0,1) & abba.trio$HG00514_2 == -1,1,0)
abba.trio$ChildPat_Mom1 <- ifelse(abba.trio$HG00514_2 %in% c(0,1) & abba.trio$HG00513_1 == -1,1,0)
abba.trio$ChildPat_Mom2 <- ifelse(abba.trio$HG00514_2 %in% c(0,1) & abba.trio$HG00513_2 == -1,1,0)
abba.trio$ChildPat_Mom <- ifelse((abba.trio$HG00514_2) %in% c(0,1) & (abba.trio$HG00513_1 & abba.trio$HG00513_2) == -1,1,0)
```

##Daughter Maternal Hap Added in Step 2 (3)

```{r step2, cache=TRUE}
colperms <-abba.trio$perm[abba.trio$step == 2 & abba.trio$HG00514_1==0]
col.df <- abba.trio %>% filter(perm %in% colperms & step <=2)
mat1perms_all <- col.df$perm[col.df$step < 2 & col.df$added=="HG00513_1"]
mat2perms_all <- col.df$perm[col.df$step < 2 & col.df$added=="HG00513_2"]
mat12perms <- intersect(mat1perms_all,mat2perms_all)
mat1perms <- which(!mat1perms_all %in% mat12perms)
mat2perms <- which(!mat2perms_all %in% mat12perms)

title_text="D2: Both Mat Added First"

cell.df <- filter(col.df, perm %in% mat12perms)
ggplot(cell.df) + geom_jitter(aes(x=as.factor(step),y=delta, color=added)) + ggtitle(title_text)
ggplot(cell.df) + geom_jitter(aes(x=as.factor(step),y=deltadelta, color=added)) + scale_y_log10() + ggtitle(title_text)
ggplot(cell.df) + geom_boxplot(aes(x=as.factor(step),y=deltadelta)) + geom_jitter(aes(x=step,y=deltadelta, color=added)) + scale_y_log10() + ggtitle(title_text)


```
```{r step2b, cache=TRUE}
cell.df <- filter(col.df, perm %in% mat1perms)
title_text="D2: Mat1 Added First"
ggplot(cell.df) + geom_jitter(aes(x=as.factor(step),y=delta, color=added)) + ggtitle(title_text)
ggplot(cell.df) + geom_jitter(aes(x=as.factor(step),y=deltadelta, color=added)) + scale_y_log10() + ggtitle(title_text)
ggplot(cell.df) + geom_boxplot(aes(x=as.factor(step),y=deltadelta)) + geom_jitter(aes(x=step,y=deltadelta, color=added)) + scale_y_log10() + ggtitle(title_text)

```

```{r step2c, cache=TRUE}
cell.df <- filter(col.df, perm %in% mat2perms)
title_text="D2: Mat2 Added First"
ggplot(cell.df) + geom_jitter(aes(x=as.factor(step),y=delta, color=added)) + ggtitle(title_text)
ggplot(cell.df) + geom_jitter(aes(x=as.factor(step),y=deltadelta, color=added)) + scale_y_log10() + ggtitle(title_text)
ggplot(cell.df) + geom_boxplot(aes(x=as.factor(step),y=deltadelta)) + geom_jitter(aes(x=step,y=deltadelta, color=added)) + scale_y_log10() + ggtitle(title_text)

```


```{r step2d, cache=TRUE}
cell.df <- filter(col.df,  !(perm  %in% union(mat1perms_all, mat2perms_all)))
title_text="D2: No Mat Added Before"
ggplot(cell.df) + geom_jitter(aes(x=as.factor(step),y=delta, color=added)) + ggtitle(title_text)
ggplot(cell.df) + geom_jitter(aes(x=as.factor(step),y=deltadelta, color=added)) + scale_y_log10() + ggtitle(title_text)
ggplot(cell.df) + geom_boxplot(aes(x=as.factor(step),y=deltadelta)) + geom_jitter(aes(x=step,y=deltadelta, color=added)) + scale_y_log10() + ggtitle(title_text)

```







##Daughter Maternal Hap Added in Step 3 (4)
```{r step3, cache=TRUE}
colperms <-abba.trio$perm[abba.trio$step == 3 & abba.trio$HG00514_1==0]
col.df <- abba.trio %>% filter(perm %in% colperms, step <=3)
mat1perms_all <- col.df$perm[col.df$step == 3 & col.df$HG00513_1==1]
mat2perms_all <- col.df$perm[col.df$step == 3 & col.df$HG00513_2==1]
mat12perms <- intersect(mat1perms_all,mat2perms_all)
mat1perms <- which(!mat1perms_all %in% mat12perms)
mat2perms <- which(!mat2perms_all %in% mat12perms)

cell.df <- filter(col.df, perm %in% mat12perms)
title_text="D3: Both Mat Added First"
ggplot(cell.df) + geom_jitter(aes(x=as.factor(step),y=delta, color=added)) + ggtitle(title_text) 
ggplot(cell.df) + geom_jitter(aes(x=as.factor(step),y=deltadelta, color=added)) + scale_y_log10() + ggtitle(title_text)
ggplot(cell.df) + geom_boxplot(aes(x=as.factor(step),y=deltadelta)) + geom_jitter(aes(x=step,y=deltadelta, color=added)) + scale_y_log10() + ggtitle(title_text)


```


```{r step3b, cache=TRUE}
cell.df <- filter(col.df, perm %in% mat1perms)
title_text="D3: Mat1 Added First"
ggplot(cell.df) + geom_jitter(aes(x=as.factor(step),y=delta, color=added)) + ggtitle(title_text)
ggplot(cell.df) + geom_jitter(aes(x=as.factor(step),y=deltadelta, color=added)) + scale_y_log10() + ggtitle(title_text)
ggplot(cell.df) + geom_boxplot(aes(x=as.factor(step),y=deltadelta)) + geom_jitter(aes(x=step,y=deltadelta, color=added)) + scale_y_log10() + ggtitle(title_text)

```

```{r step3c, cache=TRUE}
cell.df <- filter(col.df, perm %in% mat2perms)
title_text="D3: Mat2 Added First"
ggplot(cell.df) + geom_jitter(aes(x=as.factor(step),y=delta, color=added)) + ggtitle(title_text)
ggplot(cell.df) + geom_jitter(aes(x=as.factor(step),y=deltadelta, color=added)) + scale_y_log10() + ggtitle(title_text)
ggplot(cell.df) + geom_boxplot(aes(x=as.factor(step),y=deltadelta)) + geom_jitter(aes(x=step,y=deltadelta, color=added)) + scale_y_log10() + ggtitle(title_text)

```


```{r step3d, cache=TRUE}
cell.df <- filter(col.df,  !(perm  %in% union(mat1perms_all, mat2perms_all)))
title_text="D3: No Mat Added Before"
ggplot(cell.df) + geom_jitter(aes(x=as.factor(step),y=delta, color=added)) + ggtitle(title_text)
ggplot(cell.df) + geom_jitter(aes(x=as.factor(step),y=deltadelta, color=added)) + scale_y_log10() + ggtitle(title_text)
ggplot(cell.df) + geom_boxplot(aes(x=as.factor(step),y=deltadelta)) + geom_jitter(aes(x=step,y=deltadelta, color=added)) + scale_y_log10() + ggtitle(title_text)

```











##Daughter Maternal Hap Added in Step 4 (5)

```{r step4, cache=TRUE}
colperms <-abba.trio$perm[abba.trio$step == 4 & abba.trio$HG00514_1==0]
col.df <- abba.trio %>% filter(perm %in% colperms, step <=4)
mat1perms_all <- col.df$perm[col.df$step == 4 & col.df$HG00513_1==1]
mat2perms_all <- col.df$perm[col.df$step == 4 & col.df$HG00513_2==1]
mat12perms <- intersect(mat1perms_all,mat2perms_all)
mat1perms <- which(!mat1perms_all %in% mat12perms)
mat2perms <- which(!mat2perms_all %in% mat12perms)

cell.df <- filter(col.df, perm %in% mat12perms)
title_text="D4: Both Mat Added First"
ggplot(cell.df) + geom_jitter(aes(x=as.factor(step),y=delta, color=added)) + ggtitle(title_text)
ggplot(cell.df) + geom_jitter(aes(x=as.factor(step),y=deltadelta, color=added)) + ggtitle(title_text)
ggplot(cell.df) + geom_jitter(aes(x=as.factor(step),y=deltadelta, color=added)) + scale_y_log10() + ggtitle(title_text)
ggplot(cell.df) + geom_boxplot(aes(x=as.factor(step),y=deltadelta)) + geom_jitter(aes(x=step,y=deltadelta, color=added)) + scale_y_log10() + ggtitle(title_text)

```



```{r step4b, cache=TRUE}
cell.df <- filter(col.df, perm %in% mat1perms)
title_text="D3: Mat1 Added First"
ggplot(cell.df) + geom_jitter(aes(x=as.factor(step),y=delta, color=added)) + ggtitle(title_text)
ggplot(cell.df) + geom_jitter(aes(x=as.factor(step),y=deltadelta, color=added)) + scale_y_log10() + ggtitle(title_text)
ggplot(cell.df) + geom_boxplot(aes(x=as.factor(step),y=deltadelta)) + geom_jitter(aes(x=step,y=deltadelta, color=added)) + scale_y_log10() + ggtitle(title_text)

```

```{r step4c, cache=TRUE}
cell.df <- filter(col.df, perm %in% mat2perms)
title_text="D3: Mat2 Added First"
ggplot(cell.df) + geom_jitter(aes(x=as.factor(step),y=delta, color=added)) + ggtitle(title_text)
ggplot(cell.df) + geom_jitter(aes(x=as.factor(step),y=deltadelta, color=added)) + scale_y_log10() + ggtitle(title_text)
ggplot(cell.df) + geom_boxplot(aes(x=as.factor(step),y=deltadelta)) + geom_jitter(aes(x=step,y=deltadelta, color=added)) + scale_y_log10() + ggtitle(title_text)

```





##Daughter Maternal Hap Added in Step 6 (5)

```{r step5, cache=TRUE}
colperms <-abba.trio$perm[abba.trio$step == 5 & abba.trio$HG00514_1==0]
col.df <- abba.trio %>% filter(perm %in% colperms, step <=5)
mat1perms_all <- col.df$perm[col.df$step == 5 & col.df$HG00513_1==1]
mat2perms_all <- col.df$perm[col.df$step == 5 & col.df$HG00513_2==1]
mat12perms <- intersect(mat1perms_all,mat2perms_all)
mat1perms <- which(!mat1perms_all %in% mat12perms)
mat2perms <- which(!mat2perms_all %in% mat12perms)

cell.df <- filter(col.df, perm %in% mat12perms)
title_text="D5: Both Mat Added First"
ggplot(cell.df) + geom_jitter(aes(x=as.factor(step),y=delta, color=added)) + ggtitle(title_text)
ggplot(cell.df) + geom_jitter(aes(x=as.factor(step),y=deltadelta, color=added)) + ggtitle(title_text)
ggplot(cell.df) + geom_jitter(aes(x=as.factor(step),y=deltadelta, color=added)) + scale_y_log10() + ggtitle(title_text)
ggplot(cell.df) + geom_boxplot(aes(x=as.factor(step),y=deltadelta)) + geom_jitter(aes(x=step,y=deltadelta, color=added)) + scale_y_log10() + ggtitle(title_text)

```



```{r test}



```
