---
title: "R and Delta Graphs"
author: "Jessica Bonnie"
date: '2022-05-18'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require(tidyverse)
require(gridExtra)

```



```{r data_input}
concatr <- read_table('data/salmon_concat_r_results.txt',col_names = FALSE) %>% 
  rename(ngenomes=X2,usertime=X4,systemtime=X6,elapsedtime=X8,n=X10,r=X12) %>%
  select(-contains("X"))
concatd <- read_table('data/salmon_concat_delta_results.txt', col_names=FALSE) %>%
  rename(ngenomes=X2,usertime=X4,systemtime=X6,elapsedtime=X8,kmeroptimal=X10,delta=X12) %>%
  select(-contains("X"))

#grep -v Path data/human_delta_results.txt | grep -v kmer_size | awk '{print $0,NR}' > data/human_delta_results_jb.txt
humand <- read_table('data/human_delta_results_jb.txt',col_names = FALSE) %>% 
  rename(path=X1,estsize=X2,k=X3) %>%
  mutate(dk=estsize/k, scaled=dk/max(dk), Name="H.sapiens") 
salmond <- read_table('data/salmonella_delta_results_default_sketch_jb.txt',col_names = FALSE) %>%
  rename(path=X1,estsize=X2,k=X3)%>%
  mutate(dk=estsize/k, scaled=dk/max(dk), Name="S.enterica")  
ecolid <- read_table('data/phix_delta_results_jb.txt',col_names = FALSE) %>%
  rename(path=X1,estsize=X2,k=X3) %>%
  mutate(dk=estsize/k, scaled=dk/max(dk), Name="E.coli")  

deltak <- rbind(humand,salmond,ecolid)
```



```{r pressure, echo=FALSE}
deltar = max(filter(concatr,ngenomes <= 300)$r)/max(filter(concatd,ngenomes <= 300)$delta)-.2

gg_dr <- ggplot() + 
  geom_line(data=filter(concatd,ngenomes <= 300) ,mapping=aes(x=ngenomes,y=delta, color="delta"), size=1.25) +
  geom_line(data=filter(concatr,ngenomes <= 300),mapping=aes(x=ngenomes,y=r/deltar, color="r"), size=1.25) +
  scale_y_continuous(
    name = "Value of \u03b4",
    sec.axis = sec_axis(~.*deltar, name="Value of r")
  ) +
  theme_bw() +
  labs( title="Growth of r and \u03b4 with number of salmonella genomes") +
  xlab("# genomes") +
  geom_text(aes(x=100,y=2.5e6, color="delta"),label='\u03b4', size=6) +
  geom_text(aes(x=220,y=3.32e6, color="r"),label='r', size=6) +
  guides(color="none")
  
gg_dr
```

```{r save_graph}

ggplot2::ggsave(filename = "salmonella_delta_r.pdf", 
plot = gg_dr, 
device = cairo_pdf, 
dpi = 1200, 
width = 15,
height = 10, 
units = "cm")


```



```{r ksweep}
maxtable=filter(deltak,scaled==1) %>%
  select(Name,k, estsize,dk)

# tt <- ttheme_default(colhead=list(fg_params = list(parse=TRUE)),
                     # base_size = 10,
                     # padding = unit(c(2, 4), "mm"))
delta.show<-tableGrob(maxtable,rows = NULL,cols = c('Species','k','Est. Size','\u03b4'))


delta.graph <- ggplot(deltak) + 
  geom_line(mapping=aes(x=k, y=scaled, color=Name), size=1.25) + 
  theme_bw() +
  # geom_text(data=filter(deltak,scaled==1),aes(y=scaled, x=k, label=k)) +
  # annotation_custom(tableGrob(maxtable,rows = NULL,cols = c('Species','k','Est. Size','\u03b4')),
    # xmin=75, xmax=100, ymin=.75, ymax=.90) +
  scale_color_discrete(name="")  +
  ylab("Scaled " ~ d[k](S)/k) +
  xlab('kmer length') +
  ggtitle(bquote("Growth Pattern of" ~ d[k](S)/k ~ "across 3 Species"))
delta.graph

salmond.graph <- ggplot(salmond) + 
  geom_line(mapping=aes(x=k, y=dk), color='steelblue', size=1.75) + 
  theme_bw() +
  ylab(bquote( d[k](S)/k )) +
  xlab('kmer length') +
  ggtitle("Value of" ~ d[k](S)/k ~ "across kmer lengths")
salmond.graph

```

```{r humand}
ggsave(filename='scaled3species.pdf',
       plot=delta.graph,
       device = cairo_pdf, 
       dpi = 1200, 
       width = 15,
       height = 10, 
       units = "cm")

ggsave(filename='salmon_dk.pdf',
       plot=salmond.graph,
       device = cairo_pdf, 
       dpi = 1200, 
       width = 15,
       height = 10, 
       units = "cm")
