---
title: "r v z v d"
author: "Jessica Bonnie"
date: "11/2/2022"
output: html_document
---

```{r prep, echo=FALSE,warning=FALSE,include=FALSE}

require(tidyr)
require(ggplot2)
require(data.table)
require(openssl)
require(dplyr)
require(optparse)
require(callr)
require(lubridate)
codelib<-'/home/jbonnie1/dandd/dev-dandD/lib'
source(file.path(codelib,'plot_progressive.R'))

```

```{bash, eval=FALSE}
tag=salmonellarz
wkdir=/scratch4/blangme2/jessica/dandd/RECOMB/r_z_delta/
#/scratch4/blangme2/oahmed/r_and_z_results/data/global_path_filelist.txt
filelist=/scratch4/blangme2/jessica/dandd/RECOMB/r_z_delta/global_path_filelist.txt
codelib=/home/jbonnie1/dandd/dev-dandD/lib

#python lib/dandd_cmd.py tree -s ${tag} --no-canon -f ${filelist} -o $wkdir
python ${codelib}/dandd_cmd.py tree -s ${tag} -f ${filelist} -o $wkdir --exact

tag=salmonellarz_nocanon
python ${codelib}/dandd_cmd.py tree -s ${tag} -f ${filelist} -o $wkdir --exact --nocanon



```


```{bash, eval=FALSE}
tagtop=salmonellarz_concat
wkdir=/scratch4/blangme2/jessica/dandd/RECOMB/r_z_delta/
  timedir=${wkdir}/time
  mkdir ${timedir}
  #/scratch4/blangme2/oahmed/r_and_z_results/data/global_path_filelist.txt
  summary=${wkdir}/${tagtop}_bench.csv
  echo "ngen,MaxResSetSize_kb, WallClock_hms,SystemTime_sec,UserTime_sec, canon" > ${summary}
for i in $(seq 1 50); do
  fastaname=/scratch4/blangme2/oahmed/r_and_z_results/exp1_final_ref_files/ref_with_${i}_genomes_forward_only.fna
  tag=${tagtop}${i}
  cmd="echo "$fastaname" | python /home/jbonnie1/dandd/dev-dandD/lib/dandd_cmd.py --fast tree -s "${tag}" --exact -k 14 -f /dev/stdin -e 1 -o "${wkdir}
  /usr/bin/time -o ${timedir}/${tag}.out -v sh -c "${cmd}"
  mrss=$(grep "Maximum resident" ${timedir}/${tag}.out | awk '{print $NF}')
  wctime=$(grep "wall clock" ${timedir}/${tag}.out | awk '{print $NF}')
  systime=$(grep "System time" ${timedir}/${tag}.out | awk '{print $NF}')
  utime=$(grep "User time" ${timedir}/${tag}.out | awk '{print $NF}')
  echo "${i},${mrss},${wctime},${systime},${utime},1" >> ${summary}
  done
  
mkdir ${wkdir}/${tagtop}
mv ${wkdir}/${tagtop}*_* ${wkdir}/${tagtop}/.

filelist=/scratch4/blangme2/jessica/dandd/RECOMB/r_z_delta/global_path_filelist.txt

```



```{bash, eval=FALSE}
tagtop=salmonellarz_concat_nc
wkdir=/scratch4/blangme2/jessica/dandd/RECOMB/r_z_delta/
cd ${wkdir}
  timedir=${wkdir}/time
  mkdir ${timedir}
  #/scratch4/blangme2/oahmed/r_and_z_results/data/global_path_filelist.txt
  summary=${wkdir}/${tagtop}_bench.csv
  echo "ngen,MaxResSetSize_kb, WallClock_hms,SystemTime_sec,UserTime_sec, canon" > ${summary}
for i in $(seq 1 50); do
  fastaname=/scratch4/blangme2/oahmed/r_and_z_results/exp1_final_ref_files/ref_with_${i}_genomes_forward_only.fna
  tag=${tagtop}${i}
  cmd="echo "$fastaname" | python /home/jbonnie1/dandd/dev-dandD/lib/dandd_cmd.py --fast tree -s "${tag}" --no-canon --exact -k 14 -f /dev/stdin -e 1 -o "${wkdir}
  /usr/bin/time -o ${timedir}/${tag}.out -v sh -c "${cmd}"
  mrss=$(grep "Maximum resident" ${timedir}/${tag}.out | awk '{print $NF}')
  wctime=$(grep "wall clock" ${timedir}/${tag}.out | awk '{print $NF}')
  systime=$(grep "System time" ${timedir}/${tag}.out | awk '{print $NF}')
  utime=$(grep "User time" ${timedir}/${tag}.out | awk '{print $NF}')
  echo "${i},${mrss},${wctime},${systime},${utime},0" >> ${summary}
  done
  
mkdir ${wkdir}/${tagtop}
mv ${wkdir}/${tagtop}*_* ${wkdir}/${tagtop}/.

```



```{bash, eval=FALSE}
tagtop=salmonellarz_concat
wkdir=/scratch4/blangme2/jessica/dandd/RECOMB/r_z_delta_k15
cd ${wkdir}
  timedir=${wkdir}/time
  mkdir ${timedir}
  #/scratch4/blangme2/oahmed/r_and_z_results/data/global_path_filelist.txt
  summary=${wkdir}/${tagtop}_bench.csv
  echo "ngen,MaxResSetSize_kb, WallClock_hms,SystemTime_sec,UserTime_sec, canon" > ${summary}
for i in $(seq 1 50); do
  fastaname=/scratch4/blangme2/oahmed/r_and_z_results/exp1_final_ref_files/ref_with_${i}_genomes_forward_only.fna
  tag=${tagtop}${i}
  cmd="echo "$fastaname" | python /home/jbonnie1/dandd/dev-dandD/lib/dandd_cmd.py tree -s "${tag}" --exact -k 15 -f /dev/stdin -e 1 -o "${wkdir}
  /usr/bin/time -o ${timedir}/${tag}.out -v sh -c "${cmd}"
  mrss=$(grep "Maximum resident" ${timedir}/${tag}.out | awk '{print $NF}')
  wctime=$(grep "wall clock" ${timedir}/${tag}.out | awk '{print $NF}')
  systime=$(grep "System time" ${timedir}/${tag}.out | awk '{print $NF}')
  utime=$(grep "User time" ${timedir}/${tag}.out | awk '{print $NF}')
  echo "${i},${mrss},${wctime},${systime},${utime},1" >> ${summary}
  done
  
mkdir ${wkdir}/${tagtop}
mv ${wkdir}/${tagtop}*_* ${wkdir}/${tagtop}/.

filelist=/scratch4/blangme2/jessica/dandd/RECOMB/r_z_delta/global_path_filelist.txt

```



```{bash, eval=FALSE}
tagtop=salmonellarz_concat_nc
wkdir=/scratch4/blangme2/jessica/dandd/RECOMB/r_z_delta_k15
cd ${wkdir}
  timedir=${wkdir}/time
  mkdir ${timedir}
  #/scratch4/blangme2/oahmed/r_and_z_results/data/global_path_filelist.txt
  summary=${wkdir}/${tagtop}_bench.csv
  echo "ngen,MaxResSetSize_kb, WallClock_hms,SystemTime_sec,UserTime_sec, canon" > ${summary}
for i in $(seq 1 50); do
  fastaname=/scratch4/blangme2/oahmed/r_and_z_results/exp1_final_ref_files/ref_with_${i}_genomes_forward_only.fna
  tag=${tagtop}${i}
  cmd="echo "$fastaname" | python /home/jbonnie1/dandd/dev-dandD/lib/dandd_cmd.py tree -s "${tag}" --no-canon --exact -k 15 -f /dev/stdin -e 1 -o "${wkdir}
  /usr/bin/time -o ${timedir}/${tag}.out -v sh -c "${cmd}"
  mrss=$(grep "Maximum resident" ${timedir}/${tag}.out | awk '{print $NF}')
  wctime=$(grep "wall clock" ${timedir}/${tag}.out | awk '{print $NF}')
  systime=$(grep "System time" ${timedir}/${tag}.out | awk '{print $NF}')
  utime=$(grep "User time" ${timedir}/${tag}.out | awk '{print $NF}')
  echo "${i},${mrss},${wctime},${systime},${utime},0" >> ${summary}
  done
  
mkdir ${wkdir}/${tagtop}
mv ${wkdir}/${tagtop}*_* ${wkdir}/${tagtop}/.

```

### salmonella

```{bash pickle, eval=FALSE}

```

```{r salmonellarz}

all.files <- list.files(path = "/scratch4/blangme2/jessica/dandd/RECOMB/r_z_delta/salmonellarz_concat/",pattern = "deltas.csv", full.names=TRUE)
deltas<-lapply(all.files,fread)
deltas <- bind_rows(deltas)
deltas$ngenomes <- as.numeric(gsub("/scratch4/blangme2/oahmed/r_and_z_results/exp1_final_ref_files/ref_with_|_genomes_forward_only.fna","",deltas$fastas))
deltas$canon=1
deltas$delta_scaled <- (deltas$delta-min(deltas$delta))/(max(deltas$delta) - min(deltas$delta))#scale(deltas$delta)

all.files <- list.files(path = "/scratch4/blangme2/jessica/dandd/RECOMB/r_z_delta/salmonellarz_concat_nc/",pattern = "deltas.csv", full.names=TRUE)
deltas_nc<-lapply(all.files,fread)
deltas_nc <- bind_rows(deltas_nc) %>% mutate(delta=as.numeric(delta))
deltas_nc$ngenomes <- as.numeric(gsub("/scratch4/blangme2/oahmed/r_and_z_results/exp1_final_ref_files/ref_with_|_genomes_forward_only.fna","",deltas_nc$fastas))
deltas_nc$canon <- 0
deltas_nc$delta_scaled <- (deltas_nc$delta - min(deltas_nc$delta))/(max(deltas_nc$delta)  - min(deltas_nc$delta))
#scale(deltas_nc$delta)

salmonellarz1 <- bind_rows(deltas,deltas_nc) %>% select(-fastas,-title, -ngen) 
salmonellarz <- salmonellarz1 %>%
  pivot_longer(cols=contains("delta"),names_to = "title",values_to="delta") %>%
  mutate(type="value", scaled=ifelse(grepl("scale",title),"scaled","unscaled")) %>%
  select(-title, -k) %>%
  pivot_longer(cols=c(delta), names_to = "metric", values_to = "value")

omar50<-read.csv('/scratch4/blangme2/jessica/dandd/RECOMB/r_z_delta/omar_output.csv') %>% rename(ngenomes=numgenomes) %>%  mutate(across(c(starts_with("z"),starts_with("r"),-contains("time")), ~(.x-min(.x))/(max(.x)-min(.x)), .names = "{.col}_scale")) %>% mutate(across(contains("scale"),as.numeric))


omar50.canon <- omar50 %>%
  select(ngenomes,contains("withrevcomp")) %>%
  mutate(canon=1) %>% pivot_longer(cols=contains("withrevcomp"),names_to = "title",values_to="x") %>%
  mutate(name=substr(title,1,1), type=ifelse(grepl("time",title),"time","value"), scaled=ifelse(grepl("scale",title),"scaled","unscaled")) %>% select(-title) %>% ungroup() %>%
  group_by(ngenomes,canon) %>% pivot_wider(names_from=name, values_from = x)

omar50.noncanon <- omar50 %>%
  select(ngenomes,r,z,rtime,ztime,r_scale,z_scale) %>%
  mutate(canon=0) %>% 
  pivot_longer(cols=c(r,z,rtime,ztime,r_scale,z_scale),names_to = "title",values_to="x") %>%
 mutate(name=substr(title,1,1), type=ifelse(grepl("time",title),"time","value"), scaled=ifelse(grepl("scale",title),"scaled","unscaled")) %>% select(-title) %>% ungroup() %>%
  group_by(ngenomes,canon) %>% pivot_wider(names_from=name, values_from = x)

omar <- bind_rows(omar50.canon, omar50.noncanon) %>% pivot_longer(cols=c(r,z), names_to="metric", values_to="value")

bench_k14<-bind_rows(fread("/scratch4/blangme2/jessica/dandd/RECOMB/r_z_delta/salmonellarz_concat_bench.csv"),fread("/scratch4/blangme2/jessica/dandd/RECOMB/r_z_delta/salmonellarz_concat_nc_bench.csv")) %>%
  mutate(metric="delta")
bench_k15<-bind_rows(fread("/scratch4/blangme2/jessica/dandd/RECOMB/r_z_delta_k15/salmonellarz_concat_bench.csv"),fread("/scratch4/blangme2/jessica/dandd/RECOMB/r_z_delta_k15/salmonellarz_concat_nc_bench.csv")) %>%
  mutate(metric="delta_k15")
#bind_rows(bench_k14,bench_k15)
bench<- bench_k14 %>% mutate(type="time", scaled="unscaled",WallClock_sec=as.numeric(ms(WallClock_hms))) %>% select(ngenomes=ngen,type,canon,metric,value=UserTime_sec, scaled, WallClock_hms)

bind_rows(omar,salmonellarz) %>% filter(scaled=="scaled", type=="value", canon==1) %>% 
  ggplot() + 
  geom_line(aes(x=ngenomes,y=value,  color=metric), size=1) +
  ggtitle(label = "Values of r,z, and \u03b4 with cumulative salmonella genomes") +
  labs(color="", x="Number of Concatenated Salmonella Genomes", y="Scaled Metric Value") +
  theme_bw()

# 
# bind_rows(omar,salmonellarz) %>% filter(scaled=="unscaled", type=="value") %>% ggplot() + geom_line(aes(x=ngenomes,y=value, color=metric)) + facet_wrap(~canon)
# 
bind_rows(omar,bench) %>% 
  filter(scaled=="unscaled", type=="time", canon==1) %>% 
  ggplot() + geom_line(aes(x=ngenomes,y=value, color=metric), size=1) + 
  labs(y="WallClock Time (sec)", color="", x="Number of Concatenated Salmonella Genomes") +
  ggtitle("Timing Metrics for r,z, and \u03b4 with cumulative salmonella genomes") +
  theme_bw()
  
# bind_rows(omar,bench) %>% filter(scaled=="unscaled", type=="time") %>% ggplot() + geom_line(aes(x=ngenomes,y=value, color=metric)) + ylab("UserTime_sec") + facet_wrap(~canon)



```


```{r deltar, echo=FALSE}
deltaratio = max(deltarz$canon1)/max(deltarz$canon0)
deltashift = min(deltarz$canon0) - min(deltarz$canon1)/deltaratio
deltar = max(deltarz$r)/max(deltarz$canon0)
rshift=min(deltarz$canon0) - min(deltarz$r)/deltar


gg_dr <- ggplot() + 
  geom_line(data=deltarz,mapping=aes(x=ngenomes,y=canon0, color="delta-noncanon"), size=1.25) +
    geom_line(data=deltarz ,mapping=aes(x=ngenomes,y=canon1/deltaratio + deltashift, color="delta-canon"), size=1.25) +
  geom_line(data=deltarz,mapping=aes(x=ngenomes,y=r/deltar+rshift, color="r"), size=1.25) +
  # scale_y_continuous(
  #   name = "Value of \u03b4 Non-Canonical",
    # sec.axis = sec_axis(~.*deltar- min(deltarz$r)/deltar, name="Value of r (scaled to \u03b4)")
  # ) +
  theme_bw() +
  labs( title="Growth of r and \u03b4 with number of salmonella genomes") +
  xlab("# genomes") +
  ylab("Value of \u03b4 Non-Canonical")
# +
  #geom_text(aes(x=100,y=2.5e6, color="delta"),label='\u03b4', size=6) +
  #geom_text(aes(x=220,y=3.32e6, color="r"),label='r', size=6) +
  # guides(color="none")
  
gg_dr

# deltaratio = max(deltarz$canon1)/max(deltarz$canon0)
# deltashift = min(deltarz$canon0) - min(deltarz$canon1)/deltaratio
rdelta0 = max(deltarz$canon0)/max(deltarz$r)
rshift0=min(deltarz$r) - min(deltarz$canon0)/rdelta0

rdelta1 = max(deltarz$canon1)/max(deltarz$r)
rshift1=min(deltarz$r) - min(deltarz$canon1)/rdelta1

gg_dr2 <- ggplot() + 
  geom_line(data=deltarz,mapping=aes(x=ngenomes,y=canon0/rdelta0 + rshift0, color="delta-noncanon"), size=1.25) +
    geom_line(data=deltarz ,mapping=aes(x=ngenomes,y=canon1/rdelta1 + rshift1, color="delta-canon"), size=1.25) +
  geom_line(data=deltarz,mapping=aes(x=ngenomes,y=r, color="r"), size=1.25) +
  # scale_y_continuous(
  #   name = "Value of \u03b4 Non-Canonical",
    # sec.axis = sec_axis(~.*deltar- min(deltarz$r)/deltar, name="Value of r (scaled to \u03b4)")
  # ) +
  theme_bw() +
  labs( title="Growth of r and \u03b4 with number of salmonella genomes") +
  xlab("# genomes") +
  ylab("Value of r")

gg_dr2


gg_dr_scale <- ggplot() + 
  geom_line(data=deltarz,mapping=aes(x=ngenomes,y=scale(canon0), color="delta-noncanon"), size=1.25) +
    geom_line(data=deltarz ,mapping=aes(x=ngenomes,y=scale(canon1), color="delta-canon"), size=1.25) +
  geom_line(data=deltarz,mapping=aes(x=ngenomes,y=scale(r), color="r"), size=1.25) +
  # scale_y_continuous(
  #   name = "Value of \u03b4 Non-Canonical",
    # sec.axis = sec_axis(~.*deltar- min(deltarz$r)/deltar, name="Value of r (scaled to \u03b4)")
  # ) +
  theme_bw() +
  labs( title="Growth of r and \u03b4 with number of salmonella genomes") +
  xlab("# genomes") +
  ylab("Value of \u03b4 Non-Canonical")

gg_dr_scale


gg_dr_std <- ggplot() + 
  geom_line(data=deltarz,mapping=aes(x=ngenomes,y=std.canon0, color="delta-noncanon"), size=1.25) +
    geom_line(data=deltarz ,mapping=aes(x=ngenomes,y=std.canon1, color="delta-canon"), size=1.25) +
  geom_line(data=deltarz,mapping=aes(x=ngenomes,y=std.r, color="r"), size=1.25) +
  # scale_y_continuous(
  #   name = "Value of \u03b4 Non-Canonical",
    # sec.axis = sec_axis(~.*deltar- min(deltarz$r)/deltar, name="Value of r (scaled to \u03b4)")
  # ) +
  theme_bw() +
  labs( title="Growth of r and \u03b4 with number of salmonella genomes") +
  xlab("# genomes") +
  ylab("Standardized Measure Value")

gg_dr_std


gg_drz_std <- ggplot() + 
  geom_line(data=deltarz,mapping=aes(x=ngenomes,y=std.canon0, color="delta-noncanon"), size=1.25) +
    geom_line(data=deltarz ,mapping=aes(x=ngenomes,y=std.canon1, color="delta-canon"), size=1.25) +
  geom_line(data=deltarz,mapping=aes(x=ngenomes,y=std.r, color="r"), size=1.25) +
  geom_line(data=deltarz,mapping=aes(x=ngenomes,y=std.z, color="z"), size=1.25) +
  geom_line(data=deltarz,mapping=aes(x=ngenomes,y=std.rrc, color="r with revcomp"), size=1.25) +
  geom_line(data=deltarz,mapping=aes(x=ngenomes,y=std.zrc, color="z with revcomp"), size=1.25) +
  # scale_y_continuous(
  #   name = "Value of \u03b4 Non-Canonical",
    # sec.axis = sec_axis(~.*deltar- min(deltarz$r)/deltar, name="Value of r (scaled to \u03b4)")
  # ) +
  theme_bw() +
  labs( title="Growth of r, z, and \u03b4 with number of salmonella genomes") +
  xlab("# genomes") +
  ylab("Standardized Measure Value")

gg_drz_std
```


```{r deltaz, echo=FALSE}

deltaz = max(deltarz$z)/max(deltarz$canon0)
zshift=min(deltarz$canon0) - min(deltarz$z)/deltaz

gg_dz <- ggplot() + 
  geom_line(data=deltarz ,mapping=aes(x=ngenomes,y=canon0, color="delta non-canon"), size=1.25) +
  geom_line(data=deltarz ,mapping=aes(x=ngenomes,y=canon1/deltaratio + deltashift, color="delta canon"), size=1.25) + 
  geom_line(data=deltarz,mapping=aes(x=ngenomes,y=z/deltaz+zshift, color="z"), size=1.25) +
  # scale_y_continuous(
  #   name = "Value of \u03b4",
  #   sec.axis = sec_axis(~.*deltaz- min(deltarz$z)/deltaz, name="Value of z (scaled to \u03b4)")
  # ) +
  theme_bw() +
  labs( title="Growth of z and \u03b4 with number of salmonella genomes") +
  xlab("# genomes") +
   ylab("Value of \u03b4 Non-Canonical")
  #geom_text(aes(x=100,y=2.5e6, color="delta"),label='\u03b4', size=6) +
  #geom_text(aes(x=220,y=3.32e6, color="r"),label='r', size=6) +
  # guides(color="none")
  
gg_dz


```


```{r rz, echo=FALSE}

rz = max(deltarz$z)/max(deltarz$r)
#min(deltarz$r)/deltar


#min(deltarz$z)/deltaz
zrshift=min(deltarz$r) - min(deltarz$z)/rz

gg_rz <- ggplot() + 
  geom_line(data=deltarz ,mapping=aes(x=ngenomes,y=r, color="r"), size=1.25) +
  geom_line(data=deltarz,mapping=aes(x=ngenomes,y=z/rz - zrshift, color="z"), size=1.25) +
  scale_y_continuous(
    name = "Value of r*",
    sec.axis = sec_axis(~.*rz+ min(deltarz$z)/rz, name="Value of z")
  ) +
  theme_bw() +
  labs( title="Growth of z and r with number of salmonella genomes") +
  xlab("# genomes") 
#+
  #geom_text(aes(x=100,y=2.5e6, color="delta"),label='\u03b4', size=6) +
  #geom_text(aes(x=220,y=3.32e6, color="r"),label='r', size=6) +
  #guides(color="none")
  
gg_rz
```

```{r deltarz, echo=FALSE}

deltar = max(deltarz$r)/max(deltarz$delta)
deltaz = max(deltarz$z)/max(deltarz$delta)

#min(deltarz$r)/deltar
rshift=min(deltarz$delta) - min(deltarz$r)/deltar

#min(deltarz$z)/deltaz
zshift=min(deltarz$delta) - min(deltarz$z)/deltaz

gg_dzr <- ggplot() + 
  geom_line(data=deltarz ,mapping=aes(x=ngenomes,y=delta, color="\u03b4*"), size=1.25) +
  geom_line(data=deltarz,mapping=aes(x=ngenomes,y=z/deltaz+zshift, color="z"), size=1.25) +
  geom_line(data=deltarz,mapping=aes(x=ngenomes,y=r/deltar+rshift, color="r"), size=1.25) +
  scale_y_continuous(
    name = "Value of \u03b4 and r,z scaled to \u03b4*") +
# ,
#     sec.axis = sec_axis(~.*deltar, name="Value of r")
#   ) + 
  # sec.axis = sec_axis(~.*deltaz, name="Value of z") +
  
  theme_bw() +
  labs( title="Growth of r, z, and \u03b4* with number of salmonella genomes") +
  xlab("# genomes") 
#+
  #geom_text(aes(x=100,y=2.5e6, color="delta"),label='\u03b4', size=6) +
  #geom_text(aes(x=220,y=3.32e6, color="r"),label='r', size=6) +
 # guides(color="none")
  
gg_dzr
```




```{r timing}

bench_k14<-bind_rows(fread("/scratch4/blangme2/jessica/dandd/RECOMB/r_z_delta/salmonellarz_concat_bench.csv"),fread("/scratch4/blangme2/jessica/dandd/RECOMB/r_z_delta/salmonellarz_concat_nc_bench.csv")) %>%
  mutate(kstart="kstart14")
bench_k15<-bind_rows(fread("/scratch4/blangme2/jessica/dandd/RECOMB/r_z_delta_k15/salmonellarz_concat_bench.csv"),fread("/scratch4/blangme2/jessica/dandd/RECOMB/r_z_delta_k15/salmonellarz_concat_nc_bench.csv")) %>%
  mutate(kstart="kstart15")

bench<-bind_rows(bench_k14,bench_k15)
```